# Generated by Django 3.2.13 on 2022-05-25 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('city_name', models.CharField(max_length=20)),
                ('block_name', models.CharField(max_length=20)),
                ('community_name', models.CharField(max_length=20)),
                ('building_index', models.SmallIntegerField()),
                ('room_index', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password_hash', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=30, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('exp', models.BigIntegerField(default=0)),
                ('session', models.CharField(max_length=64, null=True)),
                ('vlocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.virtuallocation')),
            ],
        ),
    ]
